// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoE1UfewVHdIHY3CwZeRCF88T1eLK_qrI',
    appId: '1:287347048262:web:eee45bf92f5882f539ef47',
    messagingSenderId: '287347048262',
    projectId: 'vegemarket',
    authDomain: 'vegemarket.firebaseapp.com',
    storageBucket: 'vegemarket.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ofvCNiqu4VsXWC6-o-fUtu0w1h7zkws',
    appId: '1:287347048262:android:06b0326ddbc6ce4439ef47',
    messagingSenderId: '287347048262',
    projectId: 'vegemarket',
    storageBucket: 'vegemarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBpzqSU-_Ki1fSnGIQ5RtjtCqli8WZI0',
    appId: '1:287347048262:ios:5f3f9980e557634539ef47',
    messagingSenderId: '287347048262',
    projectId: 'vegemarket',
    storageBucket: 'vegemarket.appspot.com',
    iosBundleId: 'com.example.shopcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNBpzqSU-_Ki1fSnGIQ5RtjtCqli8WZI0',
    appId: '1:287347048262:ios:d91fff4996ebe1ad39ef47',
    messagingSenderId: '287347048262',
    projectId: 'vegemarket',
    storageBucket: 'vegemarket.appspot.com',
    iosBundleId: 'com.example.shopcart.RunnerTests',
  );
}
